services:
  laravel-template:
    build: .
    restart: always
    networks:
      - traefik
      - laravel-template
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
    depends_on:
      - laravel-template-db
  laravel-template-db:
    image: 'mariadb:10.11.4'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - laravel-template

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
  laravel-template:
    name: laravel-template
