services:
  app:
    build: .
    restart: always
    networks:
      - traefik
      - app
    labels:
      - traefik.enable=true
    env_file:
      - src/.env
    depends_on:
      - app-db
  app-db:
    image: 'mariadb:10.8.2'
    restart: always
    volumes:
      - database-data:/bitnami/mariadb
    env_file:
      - database.env
    networks:
      - app

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  app:
    name: app
