services:
  laravel-template:
    build: .
    restart: always
    networks:
      - traefik
      - laravel-template
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.laravel-template.rule=Host(`laravel-template.localhost`)'
      - 'traefik.http.services.laravel-template.loadbalancer.server.port=80'
    depends_on:
      laravel-template-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html
    env_file:
      - src/.env

  laravel-template-db:
    image: 'mariadb:11.4.7'
    restart: always
    volumes:
      - laravel-template-db:/var/lib/mysql
      # - './docker/mysql:/docker-entrypoint-initdb.d'
    environment:
      MARIADB_DATABASE: laravel-template
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: laravel-template
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
    # ports:
    #   - '3333:3306' # For test suites
    networks:
      - laravel-template

volumes:
  laravel-template-db:
    name: laravel-template-db

networks:
  traefik:
    external: true
  laravel-template:
    name: laravel-template
