services:
  app:
    build: .
    restart: always
    networks:
      - traefik
      - app
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80
    env_file:
      - src/.env
    depends_on:
      - app-db
      - app-db-replica
  app-db:
    image: 'bitnami/mariadb:10.6.7'
    restart: always
    volumes:
      - database-data:/bitnami/mariadb
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_SKIP_TEST_DB=yes
    env_file:
      - database.env
    networks:
      - app
    labels:
      - traefik.enable=false
  app-db-replica:
    image: 'bitnami/mariadb:10.6.7'
    restart: always
    depends_on:
      - app-db
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_MASTER_HOST=app-db
    env_file:
      - database.env
    networks:
      - app
    labels:
      - traefik.enable=false

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
  app:
    name: app
