services:
  laravel-template:
    build: .
    restart: always
    networks:
      - traefik
      - laravel-template
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.laravel-template.rule=Host(`laravel-template.localhost`)'
    depends_on:
      laravel-template-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html
    env_file:
      - src/.env

  laravel-template-db:
    image: 'mariadb:11.4.4'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    environment:
      MARIADB_DATABASE: laravel-template
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: laravel-template
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - laravel-template

volumes:
  database-data:
    driver: local

networks:
  traefik:
    external: true
  laravel-template:
    name: laravel-template
