services:
  laravel-template:
    build: .
    restart: always
    networks:
      - traefik
      - laravel-template
    labels:
      - traefik.enable=true
      - 'traefik.docker.network=traefik'
    env_file:
      - src/.env
  laravel-template-db:
    image: 'mariadb:11.3.2'
    restart: always
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - laravel-template

volumes:
  database-data:
    driver: local

networks:
  traefik:
    name: traefik
    external: true
  laravel-template:
    name: laravel-template
