services:
  laravel-template:
    build:
      args:
        PROD: true
    deploy:
      replicas: 2
    mem_limit: '512m'
    healthcheck:
      test: ['CMD', 'curl', '--silent', '--output', '/dev/null', '--show-error', '--fail', 'http://localhost']
      start_period: 10s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.http.routers.laravel-template.rule=Host(`laravel-template.com`) || Host(`www.laravel-template.com`)'
      - 'traefik.http.routers.laravel-template.tls=true'
      - 'traefik.http.routers.laravel-template.tls.certresolver=letsencrypt'
    depends_on:
      laravel-template-db:
        condition: service_healthy
    volumes:
      - ./src/storage/logs:/var/www/html/storage/logs
      - ./src/storage/app/public:/var/www/html/storage/app/public
  laravel-template-db:
    mem_limit: '768m'
    healthcheck:
      test:
        ['CMD', 'mariadb', '-u${MARIADB_USER}', '-p${MARIADB_PASSWORD}', '-D${MARIADB_DATABASE}', '-e', 'show tables;']
      # Need to account for upgrade times at startup
      start_period: 30s
      start_interval: 1s
      interval: 30s
      timeout: 10s
      retries: 3
