services:
  app:
    build: .
    restart: always
    container_name: app
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.port=80
    env_file:
      - src/.env
    networks:
      - app
      - traefik
    depends_on:
      - app-db
  app-db:
    image: mysql:8.0.23
    restart: always
    container_name: app-db
    env_file:
      - init-db.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app
    labels:
      - traefik.enable=false

networks:
  traefik:
    external:
      name: traefik
  app:
    name: app
