# name: build

# on: [push, pull_request]

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: extractions/setup-just@v1
#       - uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.2'
#       - run: docker network create traefik
#       - name: Run setup Docker container
#         run: |
#           cp .env-example .env
#           cd src
#           cp .env-example .env
#           just setup
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - uses: extractions/setup-just@v1
#       - uses: shivammathur/setup-php@v2
#         with:
#           php-version: '8.2'
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '20'
#       - name: Lint project
#         run: |
#           cd src
#           just install lint
#   deploy:
#     needs: ['docker', 'lint']
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to Harvey
#         if: github.ref == 'refs/heads/main'
#         uses: distributhor/workflow-webhook@v2
#         env:
#           webhook_type: 'json-extended'
#           webhook_url: ${{ secrets.WEBHOOK_URL }}
#           webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
#           data: '{ "pipeline": "deploy", "prod_compose": true, "healthcheck": ["laravel-template-laravel-template-1", "laravel-template-laravel-template-2", "laravel-template-laravel-template-db-1"] }'
